@baseUrl=http://localhost:3000
@accessToken={{authenticate.response.body.accessToken}}
###



// /# Auth Routes #/
# @name authenticate
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "login": "b0b3_5",
  "password": "123456"
}

###

// /# User Routes #/
# create and update via postman
GET {{baseUrl}}/users/jDoe4

###

DELETE {{baseUrl}}/users/13325

###
GET {{baseUrl}}/users
Authorization: Bearer {{accessToken}}

?search=J
&limit=10
&offset=0