@baseUrl=http://localhost:3000
@username=jDoe42

###



// /# User Routes #/
POST {{baseUrl}}/user/register
Content-Type: application/json

{
  "name": "Jonh Doe",
  "username": "jDoe2",
  "email":"Jdoe2@email.com",
  "password": "123456"
}

###

GET {{baseUrl}}/user/{{username}}

###

PATCH {{baseUrl}}/user/{{username}}
Content-Type: application/json

{
  "name": "Jonny"
}
###
// For development
GET {{baseUrl}}/user