@baseUrl=http://localhost:3000
@username=jDoe42
@userId=d9cca408-11fc-4cb1-aaf7-459b43d6088a
###



// /# User Routes #/
POST {{baseUrl}}/user/register
Content-Type: application/json

{
  "name": "Jonh Doe",
  "username": "jDoe3",
  "email":"Jdoe3@email.com",
  "password": "123456"
}

###

GET {{baseUrl}}/user/{{username}}

###

PATCH {{baseUrl}}/user/{{username}}
Content-Type: application/json

{
  "name": "Jonny"
}
###

DELETE {{baseUrl}}/user/{{userId}}

###
// For development
GET {{baseUrl}}/user